// POKEMON
export const GET_POKEMON_NAMES = "GET_POKEMON_NAMES";
export const GET_POKEMONS = "GET_POKEMONS";
export const CLEAR_POKEMONS = "CLEAR_POKEMONS"
export const SEARCH_POKEMON_QUERY = "SEARCH_POKEMON_QUERY";
export const CLEAR_POKEMON_QUERY = "CLEAR_POKEMON_QUERY";
export const GET_POKEMON = "GET_POKEMON";

// ALERT
export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// UTIL
export const SORT_COLLECTION = "SORT_COLLECTION";
export const ENABLE_LOADING = "ENABLE_LOADING";
export const DISABLE_LOADING = "DISABLE_LOADING";
